"use client";

import Link from "next/link";
import { motion } from "motion/react";
import { academy, classNineResults, programs, sscResults, subjects, teachers, whatsappLink } from "@/data/academy";
import { SafeImage } from "./SafeImage";
import { Reveal } from "./Reveal";

const strengths = [
  { icon: "01", title: "Concept-first learning", text: "Students understand why before memorising how." },
  { icon: "02", title: "Regular testing", text: "Frequent practice turns learning into confident performance." },
  { icon: "03", title: "Personal attention", text: "Progress is noticed, guided and strengthened consistently." },
  { icon: "04", title: "Disciplined environment", text: "A focused and respectful space made for learning." },
];

export function HomePage() {
  return <>
    <section className="home-hero"><div className="hero-pattern" aria-hidden="true"/><div className="shell hero-layout"><div className="hero-copy"><motion.p className="eyebrow" initial={false}>Classes 1–12 · Gojra</motion.p><motion.h1 initial={false}>Strong concepts.<br/><span>Confident students.</span></motion.h1><motion.p className="hero-lead" initial={false}>Focused teaching, regular assessment and individual attention—helping every student build the understanding they need to move forward.</motion.p><motion.div className="hero-actions" initial={false}><Link className="button button-accent" href="/admissions">Enquire for admission <span>↗</span></Link><a className="button button-ghost-light" href={whatsappLink("Assalam-o-Alaikum, I would like information about admission at Perfect Science Academy.")} target="_blank" rel="noreferrer">WhatsApp us <span>↗</span></a></motion.div><p className="hero-location"><span aria-hidden="true">●</span> {academy.shortAddress}</p></div><motion.div className="hero-proof" initial={false}><div className="proof-top"><span>SSC result · 2026</span><b>Top listed score</b></div><strong>{sscResults[0][1]}</strong><h2>{sscResults[0][0]}</h2><div className="proof-footer"><span>10 listed students scored</span><b>1000+</b></div></motion.div></div><div className="shell hero-stats"><div><strong>15+</strong><span>Years of teaching experience</span></div><div><strong>5</strong><span>Core subjects</span></div><div><strong>1–12</strong><span>Classes supported</span></div></div></section>

    <section className="intro section shell"><Reveal><p className="eyebrow dark">A better way to learn</p><h2>Education works best when every lesson makes the next one easier.</h2></Reveal><Reveal delay={.08}><div className="intro-copy"><p>At Perfect Science Academy, students do more than prepare for a paper. They learn concepts clearly, practise consistently and develop the confidence to solve problems independently.</p><Link href="/faculty" className="text-link">Meet our faculty <span>↗</span></Link></div></Reveal></section>

    <section className="program-section section"><div className="shell"><div className="section-heading"><Reveal><div><p className="eyebrow">Programs</p><h2>Support for every stage.</h2></div></Reveal><p>Structured learning from early foundations to focused board preparation.</p></div><div className="program-cards">{programs.map((program, index) => <Reveal key={program.title} delay={index * .06}><Link href="/admissions" className="program-card"><span>0{index + 1}</span><p>{program.years}</p><h3>{program.title}</h3><small>{program.note}</small><b>Explore program ↗</b></Link></Reveal>)}</div><div className="subjects-bar"><span>Subjects</span>{subjects.map((subject) => <b key={subject}>{subject}</b>)}</div></div></section>

    <section className="results-highlight section"><div className="shell results-layout"><Reveal><div className="results-copy"><p className="eyebrow">2026 results</p><h2>Progress you can see.</h2><p>These scores reflect focused preparation, disciplined practice and the hard work of our students.</p><Link href="/results" className="button button-light">View all results <span>↗</span></Link></div></Reveal><div className="result-cards">{sscResults.slice(0, 3).map(([name, score], index) => <Reveal key={name} delay={index * .06}><article className={index === 0 ? "featured" : ""}><span>SSC · Rank {index + 1}</span><strong>{score}</strong><h3>{name}</h3></article></Reveal>)}</div></div><div className="shell nine-result"><p><strong>{classNineResults.length}</strong> listed Class 9 students scored <b>500 or above</b> in 2026.</p><Link href="/results">See Class 9 results ↗</Link></div></section>

    <section className="method-section section shell"><div className="section-heading"><Reveal><div><p className="eyebrow dark">How students improve</p><h2>A simple system, repeated well.</h2></div></Reveal><p>Progress becomes predictable when students follow the right sequence.</p></div><div className="method-track">{["Learn", "Practice", "Test", "Review", "Improve"].map((step, index) => <div key={step}><span>0{index + 1}</span><b>{step}</b></div>)}</div><div className="strength-grid">{strengths.map((item) => <article key={item.title}><span>{item.icon}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>

    <section className="faculty-preview section"><div className="shell"><div className="section-heading faculty-heading"><Reveal><div><p className="eyebrow">Our faculty</p><h2>Experienced guidance, close to home.</h2></div></Reveal><Link href="/faculty" className="text-link light">Meet the complete faculty <span>↗</span></Link></div><div className="faculty-grid">{teachers.map((teacher, index) => <Reveal key={teacher.slug} delay={index * .06}><article><SafeImage src={teacher.image} alt={`${teacher.name}, ${teacher.subjects.join(" and ")} teacher`} className="faculty-photo" sizes="(max-width: 720px) 100vw, 33vw"/><div><span>{teacher.subjects.join(" · ")}</span><h3>{teacher.name}</h3>{teacher.experience && <p>{teacher.experience} experience</p>}</div></article></Reveal>)}</div></div></section>

    <section className="visit-section section shell"><Reveal><div><p className="eyebrow dark">Visit or contact us</p><h2>Let’s discuss the right path for your child.</h2></div></Reveal><div className="visit-card"><div><span>Academy address</span><strong>{academy.address}</strong></div><div><span>Call us</span><a href={`tel:${academy.phone.replaceAll(" ", "")}`}>{academy.phone}</a></div><div className="visit-actions"><a className="button button-primary" href={whatsappLink("Assalam-o-Alaikum, I would like to visit Perfect Science Academy and discuss admission.")} target="_blank" rel="noreferrer">Message on WhatsApp <span>↗</span></a><Link className="text-link" href="/admissions">Admission details <span>↗</span></Link></div></div></section>
  </>;
}
