import Link from "next/link";
import { academy, classNineResults, sscResults, teachers, whatsappLink } from "@/data/academy";
import { urduPrograms, urduSscNames, urduSubjects, urduTeachers } from "@/data/urdu";
import { SafeImage } from "./SafeImage";
import { Reveal } from "./Reveal";

const strengths = [
  { icon: "01", title: "تصوراتی تعلیم", text: "طلبہ رٹنے سے پہلے ہر موضوع کو سمجھتے ہیں۔" },
  { icon: "02", title: "باقاعدہ ٹیسٹ", text: "مسلسل مشق علم کو پراعتماد کارکردگی میں بدلتی ہے۔" },
  { icon: "03", title: "انفرادی توجہ", text: "ہر طالب علم کی پیش رفت پر مسلسل توجہ اور رہنمائی۔" },
  { icon: "04", title: "منظم ماحول", text: "تعلیم کے لیے پُرسکون، محفوظ اور بااحترام ماحول۔" },
];

export function UrduHomePage() {
  return <>
    <section className="home-hero"><div className="hero-pattern" aria-hidden="true"/><div className="shell hero-layout"><div className="hero-copy"><p className="eyebrow">جماعت 1–12 · گوجرہ</p><h1>مضبوط تصورات۔<br/><span>پراعتماد طلبہ۔</span></h1><p className="hero-lead">بہترین تدریس، باقاعدہ جائزہ اور انفرادی توجہ—تاکہ ہر طالب علم آگے بڑھنے کے لیے ضروری علم اور اعتماد حاصل کر سکے۔</p><div className="hero-actions"><Link className="button button-accent" href="/ur/admissions">داخلے کے لیے رابطہ کریں <span>↗</span></Link><a className="button button-ghost-light" href={whatsappLink("السلام علیکم، میں پرفیکٹ سائنس اکیڈمی میں داخلے کے بارے میں معلومات چاہتا/چاہتی ہوں۔")} target="_blank" rel="noreferrer">واٹس ایپ کریں <span>↗</span></a></div><p className="hero-location"><span aria-hidden="true">●</span> 160 جی بی کلیکی، گوجرہ</p></div><div className="hero-proof"><div className="proof-top"><span>ایس ایس سی نتیجہ · 2026</span><b>سب سے نمایاں سکور</b></div><strong>{sscResults[0][1]}</strong><h2>{urduSscNames[0]}</h2><div className="proof-footer"><span>10 طلبہ نے حاصل کیے</span><b>1000+</b></div></div></div><div className="shell hero-stats"><div><strong>15+</strong><span>سال کا تدریسی تجربہ</span></div><div><strong>5</strong><span>بنیادی مضامین</span></div><div><strong>1–12</strong><span>جماعتوں کی تعلیم</span></div></div></section>

    <section className="intro section shell"><Reveal><p className="eyebrow dark">سیکھنے کا بہتر طریقہ</p><h2>بہترین تعلیم وہ ہے جہاں ہر سبق اگلے سبق کو آسان بنائے۔</h2></Reveal><Reveal delay={.08}><div className="intro-copy"><p>پرفیکٹ سائنس اکیڈمی میں طلبہ صرف امتحان کی تیاری نہیں کرتے۔ وہ تصورات کو واضح طور پر سمجھتے، مسلسل مشق کرتے اور مسائل خود حل کرنے کا اعتماد پیدا کرتے ہیں۔</p><Link href="/ur/faculty" className="text-link">اساتذہ سے ملیے <span>↗</span></Link></div></Reveal></section>

    <section className="program-section section"><div className="shell"><div className="section-heading"><Reveal><div><p className="eyebrow">تعلیمی پروگرام</p><h2>ہر مرحلے کے لیے مکمل رہنمائی۔</h2></div></Reveal><p>ابتدائی بنیاد سے بورڈ امتحانات کی بھرپور تیاری تک منظم تعلیم۔</p></div><div className="program-cards">{urduPrograms.map((program, index) => <Reveal key={program.title} delay={index * .06}><Link href="/ur/admissions" className="program-card"><span>0{index + 1}</span><p>{program.years}</p><h3>{program.title}</h3><small>{program.note}</small><b>پروگرام دیکھیے ↗</b></Link></Reveal>)}</div><div className="subjects-bar"><span>مضامین</span>{urduSubjects.map((subject) => <b key={subject}>{subject}</b>)}</div></div></section>

    <section className="results-highlight section"><div className="shell results-layout"><Reveal><div className="results-copy"><p className="eyebrow">نتائج 2026</p><h2>کامیابی جو واضح نظر آئے۔</h2><p>یہ نتائج بہترین تیاری، مسلسل مشق اور ہمارے طلبہ کی محنت کی عکاسی کرتے ہیں۔</p><Link href="/ur/results" className="button button-light">تمام نتائج دیکھیے <span>↗</span></Link></div></Reveal><div className="result-cards">{sscResults.slice(0, 3).map(([name, score], index) => <Reveal key={name} delay={index * .06}><article className={index === 0 ? "featured" : ""}><span>ایس ایس سی · درجہ {index + 1}</span><strong>{score}</strong><h3>{urduSscNames[index]}</h3></article></Reveal>)}</div></div><div className="shell nine-result"><p><strong>{classNineResults.length}</strong> جماعت نہم کے طلبہ نے 2026 میں <b>500 یا اس سے زیادہ</b> نمبر حاصل کیے۔</p><Link href="/ur/results">جماعت نہم کے نتائج ↗</Link></div></section>

    <section className="method-section section shell"><div className="section-heading"><Reveal><div><p className="eyebrow dark">طلبہ کیسے بہتر ہوتے ہیں</p><h2>سادہ نظام، بہترین تسلسل۔</h2></div></Reveal><p>درست ترتیب کے ساتھ مسلسل محنت ترقی کو یقینی بناتی ہے۔</p></div><div className="method-track">{["سیکھیں", "مشق کریں", "ٹیسٹ دیں", "جائزہ لیں", "بہتر بنیں"].map((step, index) => <div key={step}><span>0{index + 1}</span><b>{step}</b></div>)}</div><div className="strength-grid">{strengths.map((item) => <article key={item.title}><span>{item.icon}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div></section>

    <section className="faculty-preview section"><div className="shell"><div className="section-heading faculty-heading"><Reveal><div><p className="eyebrow">ہمارے اساتذہ</p><h2>تجربہ کار رہنمائی، آپ کے قریب۔</h2></div></Reveal><Link href="/ur/faculty" className="text-link light">تمام اساتذہ سے ملیے <span>↗</span></Link></div><div className="faculty-grid">{teachers.map((teacher, index) => <Reveal key={teacher.slug} delay={index * .06}><article><SafeImage src={teacher.image} alt={`${urduTeachers[index].name}، پرفیکٹ سائنس اکیڈمی کے استاد`} className="faculty-photo" sizes="(max-width: 720px) 100vw, 33vw"/><div><span>{urduTeachers[index].subjects.join(" · ")}</span><h3>{urduTeachers[index].name}</h3>{urduTeachers[index].experience && <p>{urduTeachers[index].experience} کا تجربہ</p>}</div></article></Reveal>)}</div></div></section>

    <section className="visit-section section shell"><Reveal><div><p className="eyebrow dark">ملاقات یا رابطہ</p><h2>اپنے بچے کے بہتر تعلیمی مستقبل کے لیے ہم سے بات کریں۔</h2></div></Reveal><div className="visit-card"><div><span>اکیڈمی کا پتہ</span><strong>160 جی بی کلیکی، گوجرہ، ٹوبہ ٹیک سنگھ، پاکستان</strong></div><div><span>فون کریں</span><a dir="ltr" href={`tel:${academy.phone.replaceAll(" ", "")}`}>{academy.phone}</a></div><div className="visit-actions"><a className="button button-primary" href={whatsappLink("السلام علیکم، میں پرفیکٹ سائنس اکیڈمی کا دورہ اور داخلے کے بارے میں بات کرنا چاہتا/چاہتی ہوں۔")} target="_blank" rel="noreferrer">واٹس ایپ پر پیغام دیں <span>↗</span></a><Link className="text-link" href="/ur/admissions">داخلے کی تفصیل <span>↗</span></Link></div></div></section>
  </>;
}
